### ISSUE TITLE
pre-training data availability

### ISSUE THREAD

**Issue by timodonnell** [A-Alpha-Bio/alphabind#1]
Thanks for the very cool work! I was wondering if you had plans to make the pre-training dataset (7.5 M measurements) available?

**Comment by Remerson-aalpha** [comment]
Hi - unfortunately, no plans at the moment to release it as a package.  Some of the underlying data are already available (see e.g. https://github.com/A-AlphaBio/cov2_antibodies_variants/), and we expect that some other datasets will be made public eventually (e.g. https://www.biorxiv.org/content/10.1101/2023.12.01.569227v2), but some parts of the pretraining dataset we are not at liberty to release directly.
