### ISSUE TITLE
Ablation regarding fine-tuning step

### ISSUE THREAD

**Issue by mhj112358** [A-Alpha-Bio/alphabind#2]
Thank you for sharing this great work. It's always been speculations on how large a dataset is needed to build a generalizable model to assess the affinity of a new antibody-antigen pair and you are definitely on track to achieve that great goal of all times I believe. 

Just a quick question on the ablation studies. I'm wondering if you have tried a version without the fine-tuning step while keeping all other settings fixed and see how that model does against the full AlphaBind model? I suppose even if it does moderately okish, you can consider accelerating the process further by moderately increasing the cohort size of later AlphaSeq and BLI tests? 

Thanks again and looking forward to your reply.

**Comment by Remerson-aalpha** [comment]
Hi - thanks for your question!  We did not explicitly run that comparison for the paper but we have looked at that question in similar contexts, and the short answer is that right now it does not yet do moderately okish without any fine-tuning.  That is a very active area of research for us at the moment and hopefully we will have more to share soon.

**Comment by mhj112358** [comment]
Thank you very much for the reply. I guess that's one thing we will be looking forward to then :)
