### ISSUE TITLE
#ngc-account-and-api-key-configuration

### ISSUE THREAD

**Issue by xpan-bio** [A-Alpha-Bio/alphabind#3]
Hello, I am unable to access NVIDIA's NGC Account and API Key Configuration documentation because the link is broken(https://docs.nvidia.com/bionemo-framework/latest/access-startup.html#ngc-account-and-api-key-configuration). Could you please provide a new link where I can obtain the model weights?

**Comment by aalphabio-jharrang** [comment]
Sorry about the broken link! We'll push a patch to update that in the README.md soon.

The equivalent current link is: [https://docs.nvidia.com/bionemo-framework/1.10/access-startup.html#ngc-account-and-api-key-configuration](https://docs.nvidia.com/bionemo-framework/1.10/access-startup.html#ngc-account-and-api-key-configuration).
