### ISSUE TITLE
Docker build fails for older versions of buildkit due to unsupported `env` variant for mounting secrets

### ISSUE THREAD

**Issue by josephdviviano** [A-Alpha-Bio/alphabind#4]
I'm getting the following:

```
docker build --secret id=NGC_CLI_API_KEY --secret id=NGC_CLI_ORG -t alphabind:latest -t alphabind:${ALPHABIND_VERSION} .
[+] Building 1.7s (2/2) FINISHED                                                                                                                                                                 docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                                                             0.0s
 => => transferring dockerfile: 936B                                                                                                                                                                             0.0s
 => [internal] load metadata for nvcr.io/nvidia/clara/bionemo-framework:1.10                                                                                                                                     1.7s
Dockerfile:7
--------------------
   6 |     # Download the ESM-2nv, 3B parameter model.
   7 | >>> RUN --mount=type=secret,id=NGC_CLI_API_KEY,env=NGC_CLI_API_KEY \
   8 | >>>     --mount=type=secret,id=NGC_CLI_ORG,env=NGC_CLI_ORG \
   9 | >>>     python download_artifacts.py --model_dir ${BIONEMO_HOME}/models --models esm2nv_3b
  10 |     
--------------------
ERROR: failed to solve: unexpected key 'env' in 'env=NGC_CLI_API_KEY'
```

where (i'm using fake values below)

```
export NGC_CLI_API_KEY="YWoXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXw"
export NGC_CLI_ORG="0000000000000001"
export NGC_CLI_TEAM=""
export ALPHABIND_VERSION="1.0.0"
```

Is there something wrong with the dockerfile?

**Comment by josephdviviano** [comment]
I figured it out! The docker version needed to be updated. Maybe good to put a minimum version number in your `README.md`.

Also a quick note: this file is not currently in the repo - `bash ./alphabind/scripts/build.sh`

**Comment by aalphabio-jharrang** [comment]
Yes, the syntax for consuming Docker secret mounts as environment variables within a Dockerfile was added a few months ago in [Dockerfile buildkit syntax 1.10.0](https://docs.docker.com/build/buildkit/dockerfile-release-notes/#1100). We'll add some minimum version compatibility info for Docker/buildkit to our README.

Thanks for reporting (and for the bonus note about the vestigial reference to a `build.sh` script)! Glad that you got things working on your end 😄

**Comment by josephdviviano** [comment]
Excited to work with your tool! Thanks for making it!

Joseph (Mobile)

**Comment by aalphabio-jharrang** [comment]
Fixed in https://github.com/A-Alpha-Bio/alphabind/commit/4f8ff821334f5aa3b3c331ec2ed5fbaeabf284a6, which provides additional clarification surrounding Docker requirements. It also explicitly tags our Dockerfile with the intended compatible syntax, which results in a more interpretable error message to users if they attempt to build the image with an incompatible Docker/buildkit version.
